version: '2'

services:
  postgres:
    build: selfipvm-database
    volumes:
      - /usr/local/var/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWOR=Passw0rd
